language: java
script: travis_wait mvn -Prelease
jdk:
- oraclejdk8
deploy:
  provider: releases
  api_key: ${api_key}
  file: 
    - $HOME/build/${user}/mViewer/target/mViewer-${version}-release.tar.gz
    - $HOME/build/${user}/mViewer/target/mViewer-${version}-release.zip
  skip_cleanup: true
  on:
    tags: true